### ISSUE TITLE
Error log 

### ISSUE THREAD

**Issue by juveboss** [ddurieux/glpi_notifications#11]
Bonjour,

Je viens de voir qu'il y a des erreurs dans mes logs, il me semble que cela vient du plugin "notification" 

**php-errors.log :** 

[2019-02-20 12:57:42] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/Glpi_Crm/inc/toolbox.class.php li$
  *** PHP Notice(8): Undefined index: opt_left_image
  Backtrace :
  ...ns/notifications/inc/notification.class.php:308
  ...ns/notifications/inc/notification.class.php:109 PluginNotificationsNotification->displayOptions()
  inc/commonglpi.class.php:475                       PluginNotificationsNotification->showForm()
  ajax/common.tabs.php:92                            CommonGLPI::displayStandardTab()
  {"user":"788@server"}

[2019-02-20 12:58:52] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/Glpi_Crm/inc/toolbox.class.php li$
  *** PHP Notice(8): Undefined index: N/A
  Backtrace :
  inc/notificationtemplatetranslation.class.php:72
  inc/commondbtm.class.php:3468                      NotificationTemplateTranslation->getRawName()
  inc/commondbtm.class.php:3550                      CommonDBTM->getName()
  inc/commondbchild.class.php:445                    CommonDBTM->getNameID()
  inc/commondbchild.class.php:468                    CommonDBChild->getHistoryNameForItem()
  inc/commondbtm.class.php:1128                      CommonDBChild->post_addItem()
  ...ns/notifications/inc/notification.class.php:933 CommonDBTM->add()
  ...ns/notifications/inc/notification.class.php:140 PluginNotificationsNotification->generateNotification()
  inc/massiveaction.class.php:988                    PluginNotificationsNotification::processMassiveActionsForOneItemtype()
  inc/massiveaction.class.php:967                    MassiveAction->processForSeveralItemtypes()
  front/massiveaction.php:59                         MassiveAction->process()
  {"user":"788@server"}

Cdlt
Anthony

**Comment by ddurieux** [comment]
Fixed in commit e68a2a1e25f1561b49a5800a523bb87ae30b94b5 (for version 9.4+1.0)
