### ISSUE TITLE
Pas de retour chariot dans le champs description

### ISSUE THREAD

**Issue by Guitoon23** [ddurieux/glpi_notifications#20]
Bonjour,

Tout d'abord merci beaucoup pour ce plugin.

Je suis en version GLPI 9.3.1 avec le plugin notification 9.3+2.1

Lorsque je reçois une notification, les retours chariots ne sont pas pris en compte dans l'email de notification dans le champ description et suivi. Ils apparaissent bien pourtant dans GLPI mais pas dans l'email.

J'ai essayé avec le client outlook 2013 et thunderbird avec la même problématique.

Merci d'avance,

Cordialement,

Frédéric

**Comment by ddurieux** [comment]
Est-ce que vous avez modifié le modèle de notification (menu configuration > notifications > Modèles de notifications ) après l'avoir généré?

**Comment by Guitoon23** [comment]
Dans le doute, j'en ai recréé un. J'ai toujours le même problème.

Merci,

Frédéric

**Comment by boscorelly** [comment]
Bonjour,

une capture d'écran est possible ?

**Comment by Guitoon23** [comment]
Bonjour,

Désolé pour le retour tardif, j'étais en arrêt maladie. Vous trouverez en PJ la capture demandé.

Merci,

Cordialement,

Frédéric

![GLPI-notification](https://user-images.githubusercontent.com/50198375/57452484-2edc5b00-7264-11e9-8403-4cd39d431814.JPG)

**Comment by ddurieux** [comment]
Est-ce que tu as le même problème avec le modèle de notification de base de GLPI?
si oui, c'est plus un problème GLPI que du plugin.

**Comment by Guitoon23** [comment]
Ok, je vérifie avec le modèle de base. Merci.

Frédéric

**Comment by boscorelly** [comment]
Le ticket vient-il du collecteur de mail comme ça semble etre le cas ?

**Comment by Guitoon23** [comment]
Oui, effectivement. Mais j'ai le même soucis à la création d'un ticket dans GLPI.

Merci,

![Vue-Notif](https://user-images.githubusercontent.com/50198375/57453540-eb372080-7266-11e9-8013-9215c522ec11.JPG)
![Vue-GLPI](https://user-images.githubusercontent.com/50198375/57453543-ed00e400-7266-11e9-8819-af1d7eb5eab5.JPG)



Frédéric

**Comment by Guitoon23** [comment]
J'ai bien le même problème avec les notifications de base de GLPI :

![Vue-notif-defaut](https://user-images.githubusercontent.com/50198375/57453822-a8297d00-7267-11e9-87f4-9aff14decdd9.JPG)

Je regarde donc du côté de GLPI et non plus du plugin.

Encore merci pour votre réactivité !

Frédéric

**Comment by ddurieux** [comment]
Je clos donc
