### ISSUE TITLE
no working plugin

### ISSUE THREAD

**Issue by Smiley-k** [ddurieux/glpi_notifications#3]
I installed the plugin, created a message about new tickets but nothing happens. How it works?

GLPI 9.3.3

**Comment by ddurieux** [comment]
The plugin permit to create notification models, after you need update your notifications to use the model generated.

I will write documentation soon ;)

**Comment by boscorelly** [comment]
Hi,

first, name it with a personal name (i use ticket action - generated).

Then go to /front/notification.php
click the name you want to change
click the template tab (second tab)
Click the id of the template (not the name)
Choose the template name you generated
Save
enjoy

**Comment by ddurieux** [comment]
No news, I close, open a new issue if required
